import { Injectable } from "@angular/core"
import { Question } from "../models/question.model"

@Injectable({
    providedIn: "root",
})
export class QuestionsService {
    questions: Question[] = [
        {
            id: 1,
            type: "Nugget",
            speed: false,
            round: 1,
            points: 1,

            question:
                "Quelle musique de jeux-video s'est retrouvé dans le top 50 des musiques les plus écoutées",
            propositionsDetailed: [
                "Hollow Knight",
                "Zelda Tears of the Kingdom",
                "Halo 4",
                "Bob l'éponge: Les titans des marées",
            ],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "C",
            answerComment:
                "Le seul autre jeu est Clair Obscur Expédition 33 (29ème le 21 février 2026)",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 2,
            type: "Nugget",
            speed: false,
            round: 1,
            points: 1,

            question: "De quel film est issu cet extrait de femme qui interagissent ensemble?",
            propositionsDetailed: [
                "Star Wars",
                "Le seigneur des anneaux",
                "Harry Potter",
                "Friends",
            ],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "B",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 3,
            type: "Nugget",
            speed: false,
            round: 1,
            points: 1,

            question:
                "Écoutez bien cet extrait audio.\nQuel animal fait semblant d’etre mort pour ne pas avoir de relation avec un partenaire qui ne lui plait pas ?",
            propositionsDetailed: ["La lionne", "La libellule", "Le panda", "L'humain"],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "B",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 4,
            type: "Nugget",
            speed: false,
            round: 1,
            points: 1,

            question: "Quelles sont les paroles de cet extrait ?\nAudio après les propositions",
            propositionsDetailed: [
                "Celebrate and dance softly",
                "Celebrate and dance so free",
                "Saloperie de Dannette au fruits",
                "Sell a braid in dusk's debris",
            ],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "B",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 5,
            type: "Nugget",
            speed: false,
            round: 1,
            points: 1,

            question: "De quelle comedie musicale est extrait ce morceau ?",
            propositionsDetailed: [
                "Casanova: Opéra pop",
                "Mozart L'opéra rock",
                "Molière, l'Opéra urbain",
                "Jésus, de Nazareth à Jérusalem",
            ],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "B",
            answerComment:
                "La comédie musicale Jésus existe vraiment et a été produite entre autre par Pascal Obispo, avec Aimez-vous les uns les autres comme titre",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 6,
            type: "Nugget",
            speed: false,
            round: 1,
            points: 1,

            question: "Qui chante dans cet extrait ?",
            propositionsDetailed: ["Toad", "Titi", "Mickey", "La Grande Frite"],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "A",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 7,
            type: "SelOuPoivre",
            speed: true,
            round: 1,
            points: 1,

            question: "Extrait 1",
            propositionsDetailed: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            propositionsShort: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            answer: "Daft Punk",
            answerComment: "Derezzed, de la BO de TRON Legacy, par les Daft Punk",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 8,
            type: "SelOuPoivre",
            speed: true,
            round: 1,
            points: 1,

            question: "Extrait 2",
            propositionsDetailed: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            propositionsShort: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            answer: "Daft Les Deux",
            answerComment: "Remix des Daft Punk par Pentatonix",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 9,
            type: "SelOuPoivre",
            speed: true,
            round: 1,
            points: 1,

            question: "Extrait 3",
            propositionsDetailed: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            propositionsShort: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            answer: "Daft Pas Punk",
            answerComment: "La Serenissima (1984) par Rondo Veneziano (orchestre italien)",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 10,
            type: "SelOuPoivre",
            speed: true,
            round: 1,
            points: 1,

            question: "Extrait 4",
            propositionsDetailed: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            propositionsShort: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            answer: "Daft Pas Punk",
            answerComment: "La Lune par L'impératrice",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 11,
            type: "SelOuPoivre",
            speed: true,
            round: 1,
            points: 1,

            question: "Extrait 5",
            propositionsDetailed: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            propositionsShort: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            answer: "Daft Punk",
            answerComment: "Veridis Quo par les Daft Punk",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 12,
            type: "SelOuPoivre",
            speed: true,
            round: 1,
            points: 1,

            question: "Extrait 6",
            propositionsDetailed: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            propositionsShort: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            answer: "Daft Punk",
            answerComment: "Star Boy de The Weekend et Daft Punk",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 13,
            type: "SelOuPoivre",
            speed: true,
            round: 1,
            points: 1,

            question: "Extrait 6",
            propositionsDetailed: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            propositionsShort: ["Daft Punk", "Daft Pas Punk", "Daft Les Deux"],
            answer: "Daft Punk ou Daft Les Deux",
            answerComment:
                "C'est un morceau de Daft Punk mais remixé par Thomas Bangalter, l'un des deux Daft Punk, sans son frère",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 14,
            type: "Menu",
            speed: false,
            round: 1,
            group: 1,
            points: 1,

            title: "Et au menu nous avons...",
            question: "Au menu de quel jeu peut-on entendre cette musique ?",
            answer: "Golden Eye 007 sur la Nintendo 64",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 15,
            type: "Menu",
            speed: false,
            round: 1,
            group: 1,
            points: 1,

            title: "Et au menu nous avons...",
            question: "Au menu de quel jeu peut-on entendre cette musique ?",
            answer: "Age of Empire II",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 16,
            type: "Menu",
            speed: false,
            round: 1,
            group: 1,
            points: 1,

            title: "Et au menu nous avons...",
            question: "Au menu de quel jeu peut-on entendre cette musique ?",
            answer: "Clair Obscur Expédition 33",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 17,
            type: "Menu",
            speed: false,
            round: 1,
            group: 1,
            points: 1,

            title: "Et au menu nous avons...",
            question: "Au menu de quel jeu peut-on entendre cette musique ?",
            answer: "Mirror's Edge",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 18,
            type: "Menu",
            speed: false,
            round: 1,
            group: 2,
            points: 1,

            title: "Icones toutes seules",
            question: "De quel titre est tiré ce solo incroyable ?",
            questionComment: "3min d'audio, à arrêter manuellement",
            answer: "Sultan of Swings - Dire Straits",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 19,
            type: "Menu",
            speed: false,
            round: 1,
            group: 2,
            points: 1,

            title: "Icones toutes seules",
            question: "De quel titre est tiré ce solo incroyable ?",
            questionComment: "1min d'audio, à arrêter manuellement",
            answer: "Stairway to Heaven - Led Zeppelin",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 20,
            type: "Menu",
            speed: false,
            round: 1,
            group: 2,
            points: 1,

            title: "Icones toutes seules",
            question: "Dans quelle série peut-on entendre ce solo incroyable ?",
            answer: "Stranger Things",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 21,
            type: "Menu",
            speed: false,
            round: 1,
            group: 2,
            points: 1,

            title: "Icones toutes seules",
            question: "De quel film est tiré ce solo incroyable ?",
            answer: "Whiplash",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 22,
            type: "Menu",
            speed: false,
            round: 1,
            group: 3,
            points: 1,

            title: "La turlute",
            question: "Quelles sont les cultures qui ont influencé la naissance de la turlutte ?",
            answer: "Québécoise et Irlandaise",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 23,
            type: "Menu",
            speed: false,
            round: 1,
            group: 3,
            points: 1,

            title: "La turlute",
            question:
                "Comment s’appelle la chanteuse de turlute que l’on entend dans cet extrait ?",
            answer: "Mary Travers dite La Bolduc – Ça va venir découragez-vous pas (1930s)",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 24,
            type: "Menu",
            speed: false,
            round: 1,
            group: 3,
            points: 1,

            title: "La turlute",
            question: "Dans quel titre peut-on entendre ce passage turluté ?",
            answer: "Reel turluté",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 25,
            type: "Menu",
            speed: false,
            round: 1,
            group: 3,
            points: 1,

            title: "La Turlute",
            question: "Qui a composé cet extrait de turlute acadienne montréalaise ?",
            answer: "Marie-Claire Saindon",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 26,
            type: "Addition",
            speed: true,
            round: 1,
            points: 3,

            title: "Changeons de style",
            question: "Quel est le chanteur original de cette chanson reprise au style baroque ?",
            answer: "Jean-Jacques Goldman - Je marche seul",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 27,
            type: "Addition",
            speed: true,
            round: 1,
            points: 3,

            title: "Changeons de style",
            question: "Quel est le titre de cette chanson reprise en gospel ?",
            answer: "Stayin' Alive - Bee Gees",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 28,
            type: "Addition",
            speed: true,
            round: 1,
            points: 3,

            title: "Changeons de style",
            question: "Quel est le titre de cette chanson reprise en dark country ?",
            answer: "In the air tonight - Phil collins",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 29,
            type: "Addition",
            speed: true,
            round: 1,
            points: 3,

            title: "Changeons de style",
            question: "Quel est le titre de cette chanson reprise en mode « opéra rock » ?",
            answer: "Ooops I did it again - Britney Spears",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 30,
            type: "Addition",
            speed: true,
            round: 1,
            points: 3,

            title: "Changeons de style",
            question:
                "Quel est le titre de cette chanson reprise en mode Soul Jazz des années 50s?",
            answer: "Baby Shark",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 31,
            type: "Addition",
            speed: true,
            round: 1,
            points: 3,

            title: "Changeons de style",
            question: "Quel est le titre de cette chanson reprise en mode Reggae ?",
            answer: "Lose Yourself - Eminem",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 32,
            type: "Tips",
            speed: true,
            round: 1,
            points: 0,

            question: "Complétez les paroles",
            answer: "AAAAAAAAH",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },

        {
            id: 33,
            type: "Nugget",
            speed: false,
            round: 2,
            points: 1,

            question: "Qui est Victor Borge ?",
            propositionsDetailed: [
                "Un célèbre chef d'orchestre",
                "Un célèbre pianiste",
                "Un célèbre humoriste",
                "Les trois à la fois",
            ],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "D",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 34,
            type: "Nugget",
            speed: false,
            round: 2,
            points: 1,

            question:
                "Quelle chanson représentant la France a l’eurovision a eu le meilleur classement?",
            propositionsDetailed: [
                "Je n'ai que mon âme - Natasha St-Pier (2001)",
                "Mon amour - Slimane (2024)",
                "Voilà - Barbara Pavi (2021)",
                "L'amour à la française - Fatals Picards (2007)",
            ],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "C",
            answerComment:
                "Fatal Picard – 22ème\nNatasha St Pier – 4ème\nSlimane – 4ème\nBarbara Pavi – 3ème",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 35,
            type: "Nugget",
            speed: false,
            round: 2,
            points: 1,

            question:
                "Pour la cérémonie d’ouverture du championnat du monde de quel jeux-video cette chanson a été chanté ?",
            propositionsDetailed: ["Pokemon", "League of Legends", "Dota 2", "Microsoft Excel"],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "B",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 36,
            type: "Nugget",
            speed: false,
            round: 2,
            points: 1,

            question:
                "Vous vous rappelez de l'extrait que vous avez entendu dans la première partie avant la question sur la lib.lulle ?\nEt bien qui c'était ?",
            propositionsDetailed: [
                "Un jeune Samuel L Jackson",
                "Un jeune Morgan Freeman",
                "Un jeune James Earl Jones",
                "Un jeune Robert Downey Junior",
            ],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "B",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 37,
            type: "Nugget",
            speed: false,
            round: 2,
            points: 1,

            question:
                "Quelle est la particularite de l’homme que l’on entend jouer de la flute de pan ?",
            propositionsDetailed: [
                "Il lui manque un poumon",
                "Il n'existe pas (IA)",
                "Il n'as pas de mains",
                "Il est champion du monde de Beatbox",
            ],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "C",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 38,
            type: "Nugget",
            speed: false,
            round: 2,
            points: 1,

            question: "Pour quel produit cette parodie de pub a ete faite ?",
            propositionsDetailed: [
                "Du PQ avec la moustache d’Hitler",
                "Un tapis de toilette avec la moustache d’Hitler",
                "Une brosse à toilette avec la moustache d’Hitler",
                "Un rasoir designé spécifiquement pour se faire la moustache de Charlie Chaplin dans le film Le Dictateur",
            ],
            propositionsShort: ["A", "B", "C", "D"],
            answer: "C",
            answerComment:
                "Petit clin d'oeil à Arisch Weiss (blanc aryen), Eva Braun (marron Eva) et Himmler Blau (bleu himmler)",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 39,
            type: "SelOuPoivre",
            speed: true,
            round: 2,
            points: 1,

            question: "Ernst Gräfenberg",
            propositionsDetailed: ["Point G", "Point Godwin", "Les deux"],
            propositionsShort: ["Point G", "Point Godwin", "Les deux"],
            answer: "Point G",
            answerComment:
                "Médecin obstétricien allemand juif, le point G est nommé après lui pour ses recherches",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 40,
            type: "SelOuPoivre",
            speed: true,
            round: 2,
            points: 1,

            question: "Intro de Pornhub",
            propositionsDetailed: ["Point G", "Point Godwin", "Les deux"],
            propositionsShort: ["Point G", "Point Godwin", "Les deux"],
            answer: "Point G",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 41,
            type: "SelOuPoivre",
            speed: true,
            round: 2,
            points: 1,

            question: "Se cache dans des endroits sombres",
            propositionsDetailed: ["Point G", "Point Godwin", "Les deux"],
            propositionsShort: ["Point G", "Point Godwin", "Les deux"],
            answer: "Les deux",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 42,
            type: "SelOuPoivre",
            speed: true,
            round: 2,
            points: 1,

            question: "Musique de la liste de Schindler",
            propositionsDetailed: ["Point G", "Point Godwin", "Les deux"],
            propositionsShort: ["Point G", "Point Godwin", "Les deux"],
            answer: "Point Godwin",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 43,
            type: "SelOuPoivre",
            speed: true,
            round: 2,
            points: 1,

            question: "Extrait de Inglorious bastards",
            propositionsDetailed: ["Point G", "Point Godwin", "Les deux"],
            propositionsShort: ["Point G", "Point Godwin", "Les deux"],
            answer: "Les deux",
            answerComment: "Petit passage de scène de cul dans l'extrait",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 44,
            type: "SelOuPoivre",
            speed: true,
            round: 2,
            points: 1,

            question: "Fifty shades of grey",
            propositionsDetailed: ["Point G", "Point Godwin", "Les deux"],
            propositionsShort: ["Point G", "Point Godwin", "Les deux"],
            answer: "Point G",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 45,
            type: "Menu",
            speed: false,
            round: 2,
            group: 1,
            points: 1,

            title: "What does the fox say",
            question: "Comment s’appelle le cri du renard ?",
            answer: "Le glapissement",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 46,
            type: "Menu",
            speed: false,
            round: 2,
            group: 1,
            points: 1,

            title: "What does the fox say",
            question: "De quel film est tiré cet extrait ?",
            answer: "Robin des bois de Disney",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 47,
            type: "Menu",
            speed: false,
            round: 2,
            group: 1,
            points: 1,

            title: "What does the fox say",
            question:
                "Complétez les paroles\n\nEt tout ces moments entre nous, m’apprendrons le prix…",
            answer: "Bonheur",
            answerComment:
                "Tiré de la comédie musicale Le petit prince, dialogue entre le prince et le renard dans le titre Apprivoise-moi",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 48,
            type: "Menu",
            speed: false,
            round: 2,
            group: 1,
            points: 1,

            title: "What does the fox say",
            question:
                "V ou F, Mike « Tails » Power est un acteur de film pour adulte qui a choisi son nom en hommage à l’acolyte aux deux « queue » de Sonic le hérisson ?",
            answer: "Faux",
            answerComment: "Le nom complet du renard est Mike Tails Prower",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 49,
            type: "Menu",
            speed: false,
            round: 2,
            group: 2,
            points: 1,

            title: "La Magie d'Internet",
            question: "De quel film vient l’extrait qui a servi à faire cette musique ?",
            answer: "Le Seigneur des Anneaux: Les Deux Tours",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 50,
            type: "Menu",
            speed: false,
            round: 2,
            group: 2,
            points: 1,

            title: "La Magie d'Internet",
            question:
                "De quelle série vient l’extrait qui a servi à faire cette musique ? Et de quelle saison",
            answer: "Stranger Things - saison 4",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 51,
            type: "Menu",
            speed: false,
            round: 2,
            group: 2,
            points: 1,

            title: "La Magie d'Internet",
            question:
                "Dans la parodie Seagull, Stop it now, qu’a trouvé Yoda sous cette grosse buche ?",
            answer: "Un petit bout de bois",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 52,
            type: "Menu",
            speed: false,
            round: 2,
            group: 2,
            points: 1,

            title: "La Magie d'Internet",
            question: "De quel film vient les paroles de cette chanson ?",
            answer: "Star Wars episode 3: La revanche des Siths",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 53,
            type: "Menu",
            speed: false,
            round: 2,
            group: 2,
            points: 1,

            title: "Blind Test pour aveugle",
            question: "Question en braille",
            answer: "K-Maro, Femme like U",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 54,
            type: "Menu",
            speed: false,
            round: 2,
            group: 3,
            points: 1,

            title: "Blind Test pour aveugle",
            question: "Question en braille",
            answer: "K-Maro, Let’s go",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 55,
            type: "Menu",
            speed: false,
            round: 2,
            group: 3,
            points: 1,

            title: "Blind Test pour aveugle",
            question: "Question en braille",
            answer: "K-Maro, sous l’œil de l’ange",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 56,
            type: "Menu",
            speed: false,
            round: 2,
            group: 3,
            points: 1,

            title: "Blind Test pour aveugle",
            question: "Question en braille",
            answer: "Gilbert Montagné - On va s'aimer",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 57,
            type: "Addition",
            speed: true,
            round: 2,
            points: 3,

            title: "Toutes les réponses sont chauves",
            question: "Acteur célèbre ayant joué dans la série Fast and furious",
            questionComment: "La bonne réponse la plus fréquente est éliminée",
            answer: "Vin diesel\nDwayne Johnson\nJason Statham\nTyrese Gibson\nDjimon Hounsou",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 58,
            type: "Addition",
            speed: true,
            round: 2,
            points: 3,

            title: "Toutes les réponses sont chauves",
            question: "Méchant de disney",
            questionComment: "La bonne réponse la plus fréquente est éliminée",
            answer: "Hades - Hercule\nStomboli – Pinocchio\nChef skinner – Ratatouille\nEdgar Balthazar – Les aristochats",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 59,
            type: "Addition",
            speed: true,
            round: 2,
            points: 3,

            title: "Toutes les réponses sont chauves",
            question: "Mentors chauves",
            questionComment: "La bonne réponse la plus fréquente est éliminée",
            answer: "Charles Xavier – X-men\nMorpheus – Matrix\nMace Windu/Yoda – Star Wars\nOncle Iroh - Avatar",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 60,
            type: "Addition",
            speed: true,
            round: 2,
            points: 3,

            title: "Toutes les réponses sont chauves",
            question: "Un animateur",
            questionComment: "La bonne réponse la plus fréquente est éliminée",
            answer: "La Grande Frite\nHowie Mandel\nSteve Harvey\nPhilippe Etchebest\nVincent Lagaffe",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 61,
            type: "Addition",
            speed: true,
            round: 2,
            points: 3,

            title: "Toutes les réponses sont chauves",
            question: "Acteur de film pour adulte",
            questionComment: "Plus de pénalitée de réponse fréquente",
            answer: "Johnny Sins",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 62,
            type: "Addition",
            speed: true,
            round: 2,
            points: 3,

            title: "Toutes les réponses sont chauves",
            question:
                "Un jeu de mot pourri sur les chauves que j’ai jamais entendu, bonus si on me fait rire",
            questionComment: "La bonne réponse la plus fréquente est éliminée",
            answer: "tbd",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 63,
            type: "Tips",
            speed: true,
            round: 2,
            points: 0,

            question:
                "Je pourrais vous demander le compositeur et la reponse serait Hans Zimmer mais vous resteriez sur votre faim et on aime pas ca au poutine quiz alors je vais vous demander qui chante a la place… Cette question est beaucoup trop longue pour ce que c’est…",
            answer: "Raye - Titre Click Clack",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
        {
            id: 64,
            type: "PoutineDeLaMort",
            speed: false,
            round: 3,
            points: 0,

            question:
                "1. Comment s'appelerait la chanson Blue si le héro était rouge ?\n2. V ou F, Edith Piaf devait se prendre de sacré ligne pour voir la vie en rose ?\n3. Dans la chanson je te survivrai, à quoi survivrai Jean-Pierre François ?\n4. Pensez-vous qu'une emission comme la voie mais où les juges jugeraient uniquement sur le physique aurait du succès ?\n 5. Et pensez-vous que j'y ai ma chance ?\n6. Allé vous pouvez nous le dire après tout ce temps, qui a volé l'orange du marchand ?\n7. Comment s'appelerait Arian Grande si elle était très petite ?\n8. V ou F, certaines femmes enceintes diffusent du bon gros son ?\n9. Complétez ces paroles, Tiens voilà du...\n10. Et enfin, si vous demandiez de l'aide à Rick Astley, est-ce qu'il vous laisserait tomber ?",
            answer: "NA",

            showQuestion: false,
            propositionsStep: 0,
            locked: false,
            showAnswer: false,
        },
    ]
}
